config/routes.rb
Rails.application.routes.draw do

  # Routing for unsynced
  get 'unsynced/new'
  get 'unsynced/index'
  get 'unsynced/new', to: 'unsynced#new'
  post 'unsynced/new', to: 'unsynced#create'
  get 'unsynced/commit', to: 'unsynced#commit'
  
  # Routing for whales (which is also the primary page)
  get 'whales/delete', to: 'whales#delete'
  get '/main', to: 'whales#main'
  get '/sync', to: 'whales#sync'
  get '/purgecache', to: 'whales#purge_cache'
  get '/cache_ratio', to: 'whales#cache_ratio'

  
  # Root route redirect
  # Once login is implemented route to login page
  root 'whales#main'
  
  resources :whales
  resources :unsynced
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Whales proxy site made by Lim Daekoon<br>
    Email: <a href="mailto:daekoon_lim@hotmail.com">daekoon_lim@hotmail.com</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Whales Proxy", main_path, id: "logo" %>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<%= 
 
  # Metadatum(Last_Saved) is used in sidebar, and since sidebar is always
  # open for all pages object Last_sync is just loaded directly in sidebar
  
  @LastSync = Metadatum.find_by name: "Last_Sync"

  # Check cache for Last sync
  # @LastSync = Rails.cache.fetch("Last_Sync") { 
  #   # No cache found
  #   puts 'No cache found. Generating...';
  #   Metadatum.find_by name: "Last_Sync"
  # }   
  #Last sync doesn't exist, create new object
  if @LastSync == nil 
    @LastSync = Metadatum.new(name: "Last_Sync", value: "Never")
    @LastSync.save
  end
%>

<div class = "col-sm-3 col-md-2 sidebar">
  <b>Server Operations</b>
  <ul>
    <li><%= link_to "Sync with main server", sync_path %>
    <br>Last sync: <%= @LastSync.value %></li>
    <li><%= link_to "Cache Hit Ratio", cache_ratio_path %></li>
    <li><%= link_to "Purge Cache", purgecache_path %></li>
  </ul>
  <b>Navigation</b>
  <ul>
    <li><%= link_to "See all whales", main_path %></li>
    <li><%= link_to "See all unsaved commits", unsynced_index_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whales Proxy Server</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidebar' %>
    <div class ="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>